[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.98.0"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.98.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://join.botkube.io"
  to = "https://join.slack.com/t/botkube/shared_invite/zt-19iz5t5ti-TwZxDga1scQy5DsiqWF8qg/"
  force = true
  # The default HTTP status code is 301, but you can define a different one.
  status = 302
